#!/usr/bin/env node

function assert(value) {
	if (!value) {
		error('Got "' + value + '",\nExpected:  a truthy value');
	}
}

assert.is = function(lhs, rhs) {
	if (lhs !== rhs) {
		error('Got "' + lhs + '",\nExpected:  "' + rhs + '"');
	}
};

assert.eq = function(lhs, rhs) {
	lhsS = JSON.stringify(lhs);
	rhsS = JSON.stringify(rhs);
	if (lhsS !== rhsS) {
		error('Got "' + lhsS + '",\nExpected:  "' + rhsS + '"');
	}
};

function error(msg) {
	console.log("\nError: " + msg);
	Error.prepareStackTrace = function(e, stackTrace) {
		return stackTrace;
	};
	var err = new Error();

	var callSite = err.stack[2];
	var filename = callSite.getFileName();
	var file = require('fs').readFileSync(filename, 'utf8');
	var relative = require('path').relative(process.cwd(), filename);
	var line = callSite.getLineNumber();
	var column = callSite.getColumnNumber();

	console.log("\nFile: " + relative);
	console.log("Line: " + line);
	console.log("\n" + file.split('\n')[line-1].replace(/\t/g, ' '));
	console.log(Array(column).join(' ') + "^");
	err.stack.splice(0, 2);
	console.log("\n" + err.stack.join('\n'));
	process.exit(1);
}

assert.is(1 + 2, 3);

var mk = require('./lib/mk');

assert.is(mk.trim('a\n  \nb'), 'a\n\nb');
assert.is(mk.trim('foo\n  \n  bar  \n\t\nzot'), 'foo\n\n  bar  \n\nzot');
assert.is(mk.trim('\n\nfoo\n\n  \n'), 'foo');
assert.is(mk.trim('one\n   \ntwo\t  \n \t\f\r\nthree \n\n '), 'one\n\ntwo\t  \n\nthree ');

assert.is(mk.untabify('\t'), '    ');
assert.is(mk.untabify(' \t'), '    ');
assert.is(mk.untabify('  \t'), '    ');
assert.is(mk.untabify('   \t'), '    ');
assert.is(mk.untabify('    \t'), '        ');
assert.is(mk.untabify('\tbar'), '    bar');
assert.is(mk.untabify('*\tbar'), '*   bar');
assert.is(mk.untabify(' *\t two'), ' *   two');
assert.is(mk.untabify(' *\t\t three'), ' *       three');
assert.is(mk.untabify('\t1\t2\n  \t\t zot\t'), '    1   2\n         zot    ');

assert.eq(mk.split('one\ntwo\n\nthree\n\n\nfour'), ['one\ntwo', 'three', 'four']);

assert.is(mk.type('Hello world!'), 'paragraph');
assert.is(mk.type('# foo'), 'heading');
assert.is(mk.type(' # foo'), 'paragraph');
assert.is(mk.type('###### foo'), 'heading');
assert.is(mk.type('####### foo'), 'paragraph');
assert.is(mk.type('    foo'), 'codeBlock');
assert.is(mk.type('   foo'), 'paragraph');
assert.is(mk.type('*   foo'), 'codeBlock');
assert.is(mk.type('*  foo'), 'ul');
assert.is(mk.type('* list'), 'ul');
assert.is(mk.type('*list'), 'paragraph');
assert.is(mk.type('#. list'), 'ol');
assert.is(mk.type('#.list'), 'paragraph');
assert.is(mk.type('> text'), 'blockquote');
assert.is(mk.type('>text'), 'paragraph');
assert.is(mk.type('<ins>text</ins>'), 'html');
assert.is(mk.type(' <ins>text</ins>'), 'html');
assert.is(mk.type('A <ins>text</ins>'), 'paragraph');
assert.is(mk.type('* <ins>text</ins>'), 'ul');

assert.is(mk.handle('This is a paragraph.'), '<p>This is a paragraph.');
assert.is(mk.handle('A two-line\nparagraph.'), '<p>A two-line\nparagraph.');

assert.is(mk.handle('# Title'), '<h1>Title</h1>');
assert.is(mk.handle('###### Subsubsubsubsubtitle'), '<h6>Subsubsubsubsubtitle</h6>');
assert.is(mk.handle('####### Subsubsubsubsubtitle'), '<p>####### Subsubsubsubsubtitle');
assert.is(mk.handle('    while (true)\n        repeat();'), '<pre><code>while (true)\n    repeat();</code></pre>');
assert.is(mk.handle('    while (true)\n*       repeat();'), '<pre><code>while (true)\n<b>    repeat();</b></code></pre>');
//assert.is(mk.handle('    <!doctype html>\n    <html>&c.</html>'), '<pre><code>&lt;!doctype html&gt;\n&lt;html&gt;&amp;c.&lt;&sol;html&gt;</code></pre>');

assert.is(mk.handle('* foo\n* bar'), '<ul>\n<li>foo\n<li>bar\n</ul>');
assert.is(mk.handle('* foo\n* bar\n  zot'), '<ul>\n<li>foo\n<li>bar\n  zot\n</ul>');
assert.is(mk.handle('#. foo\n#. bar'), '<ol>\n<li>foo\n<li>bar\n</ol>');

assert.is(mk.handle('<hr>'), '<hr>');

assert.is(mk.handle('> First line\n> another one.'), '<blockquote><p>First line\nanother one.\n</blockquote>');
assert.is(mk.handle('> First paragraph\n> inside a blockquote.\n> \n> Second.'), '<blockquote><p>First paragraph\ninside a blockquote.\n<p>Second.\n</blockquote>');

assert.is(mk.escape("<h1 class='foo'>One & two</h1>"), "&lt;h1 class=&#39;foo&#39;&gt;One &amp; two&lt;/h1&gt;");

assert.is(mk.filter('X & Y'), 'X &amp; Y');
assert.is(mk.filter('0 < a href > d < /a >'), '0 &lt; a href &gt; d &lt; /a &gt;');

assert.is(mk.codify('a `span` of `<code>`'), 'a <code>span</code> of <code>&lt;code&gt;</code>');
assert.is(mk.codify('`a && b << 2 + ""`'), '<code>a &amp;&amp; b &lt;&lt; 2 + &quot;&quot;</code>');
//assert.is(mk.codify('`/italic/ and *bold* and _link to_ (foo.html)`'), '<code>&sol;italic&sol; and &ast;bold&ast; and &lowbar;link to&lowbar; (foo.html)</code>');
assert.is(mk.filter('`/foo_bar/ & 1` looks like /foo_bar/ & 1'), '<code>/foo_bar/ &amp; 1</code> looks like <i>foo_bar</i> &amp; 1');

//assert.is(mk.codify('`\\``'), '<code>`</code>');
//assert.is(mk.codify('`\\`` `\\\\` `\\\\\\``'), '<code>`</code> <code>\\</code> <code>\\`</code>');
//assert.is(mk.codify('A \\` outside a `<code>` block'), "A ` outside a <code>&lt;code&gt;</code> block");
//assert.is(mk.codify('&`code`'), '&amp;<code>code</code>');

assert.is(mk.italicize('Its /italic/, /and this/.'), 'Its <i>italic</i>, <i>and this</i>.');
assert.is(mk.italicize('And // this?'), 'And // this?');
assert.is(mk.italicize('(/This, too/.)'), '(<i>This, too</i>.)');
assert.is(mk.italicize('/(This, too.)/'), '<i>(This, too.)</i>');
assert.is(mk.italicize('/Really/?'), '<i>Really</i>?');
assert.is(mk.italicize('/Really!/'), '<i>Really!</i>');
assert.is(mk.italicize('/a/ /b/ /c/ /d/'), '<i>a</i> <i>b</i> <i>c</i> <i>d</i>');

assert.is(mk.italicize('This is /A/B testing/!'), 'This is <i>A/B testing</i>!');
assert.is(mk.italicize('This is not: and/or/something'), 'This is not: and/or/something');
assert.is(mk.italicize('1 / 2 * 3 / 4 + /a / b / c/.'), '1 / 2 * 3 / 4 + <i>a / b / c</i>.');
assert.is(mk.italicize('/Italic/ starts, /in middle/, /ends/'), '<i>Italic</i> starts, <i>in middle</i>, <i>ends</i>');
assert.is(mk.italicize('A // comment?'), 'A // comment?');
assert.is(mk.italicize("across /the\nnewline/, too"), "across <i>the\nnewline</i>, too");
assert.is(mk.italicize('<code>printf()</code> w/ extra sauce'), '<code>printf()</code> w/ extra sauce');
assert.is(mk.italicize('https://this.is.url.com/'), 'https://this.is.url.com/');
assert.is(mk.italicize('file:///path.to/some/file/'), 'file:///path.to/some/file/');

assert.is(mk.boldify('*this is bold*'), '<b>this is bold</b>');
assert.is(mk.boldify('*this* *too* *is*'), '<b>this</b> <b>too</b> <b>is</b>');
assert.is(mk.boldify('*multiple words*'), '<b>multiple words</b>');
assert.is(mk.boldify('inside *a sentence* works'), 'inside <b>a sentence</b> works');

assert.is(mk.boldify('but 2 * 3 * 4 is not *bold*'), 'but 2 * 3 * 4 is not <b>bold</b>');
assert.is(mk.boldify('nor is a*b*c nor a*b* nor *a*b'), 'nor is a*b*c nor a*b* nor *a*b');

assert.is(mk.boldify(mk.italicize('*this /sentence is* invalid/')), '<b>this <i>sentence is</b> invalid</i>');

assert.is(mk.italicize(mk.boldify('*this /sentence is* invalid/')), '<b>this <i>sentence is</b> invalid</i>');

var bracketMatcher = function(string) {
	var pattern = /<((?:[^<>]*<(?:[^<>]*<[^<>]*>)*[^<>]*>)*[^<>]*)>/;
	var match = string.match(pattern);
	return match ? match[1] : null;
}

assert.is(bracketMatcher('<hello>'), 'hello');
assert.is(bracketMatcher('a <b> c'), 'b');
assert.is(bracketMatcher('a <first> <second> c'), 'first');
assert.is(bracketMatcher('<less <than>'), 'than');
assert.is(bracketMatcher('<a <b> c>'), 'a <b> c');
assert.is(bracketMatcher('<a <b> and <c> d>'), 'a <b> and <c> d');
assert.is(bracketMatcher('<a <b <c> <d> e> and <f <g> h> i>'), 'a <b <c> <d> e> and <f <g> h> i');

assert.is(bracketMatcher('<<<>>>'), '<<>>');
assert.is(bracketMatcher('<<<<>>>>'), '<<>>');
assert.is(bracketMatcher('<<<<><><>>>>'), '<<><><>>');
assert.is(bracketMatcher('<foo<bar>>>>'), 'foo<bar>');
assert.is(bracketMatcher('<<<<foo<bar>>'), 'foo<bar>');

assert.is(bracketMatcher('<4<3<2<1'), null);
assert.is(bracketMatcher('<4<3<2<1>'), '1');
assert.is(bracketMatcher('<4<3<2<1>>'), '2<1>');
assert.is(bracketMatcher('<4<3<2<1>>>'), '3<2<1>>');
assert.is(bracketMatcher('<4<3<2<1>>>>'), '3<2<1>>');

assert.is(mk.linkify('_previous_ and _next_'), '<a>previous</a> and <a>next</a>');
assert.is(mk.linkify('_Google_ (http://google.com/)'), "<a href='http://google.com/'>Google</a>");
assert.is(mk.linkify("_Google_ (http://google.com/?q=foo&x='abc')"), "<a href='http://google.com/?q=foo&amp;x=&#39;abc&#39;'>Google</a>");
assert.is(mk.linkify("_A (band)_ (http://en.wikipedia.org/wiki/A_(band))"), "<a href='http://en.wikipedia.org/wiki/A_(band)'>A (band)</a>");
assert.is(mk.linkify("_Law (band)_ (http://en.wikipedia.org/wiki/Law_(band)_(disambiguation))"), "<a href='http://en.wikipedia.org/wiki/Law_(band)_(disambiguation)'>Law (band)</a>");
assert.is(mk.linkify("_Hypothetical URL_ (http://eval.com/(+ 1 (+ 2 3)))"), "<a href='http://eval.com/(+ 1 (+ 2 3))'>Hypothetical URL</a>");
assert.is(mk.linkify("_Hypothetical URL_ (http://eval.com/(+ 1 (+ 2 3) (- 2 3) ()()()))"), "<a href='http://eval.com/(+ 1 (+ 2 3) (- 2 3) ()()())'>Hypothetical URL</a>");
assert.is(mk.linkify("_This fails_ (http://eval.com/(+ 1 (+ 2 (+ 3 4))))"), "<a>This fails</a> (http://eval.com/(+ 1 (+ 2 (+ 3 4))))");

assert.is(mk.linkify("V8's _structured\nstack trace_ (http://code.google.com/p/v8/wiki/JavaScriptStackTraceApi)"), "V8's <a href='http://code.google.com/p/v8/wiki/JavaScriptStackTraceApi'>structured\nstack trace</a>");

assert.is(mk("    int x;\n    \n    x = 1;"), "<pre><code>int x;\n\nx = 1;</code></pre>\n");

assert.is(mk('    \\`'), '<pre><code>\\`</code></pre>\n');

assert.is(mk.dashify('-- stuff---more --'), '&ndash; stuff&mdash;more &ndash;');
assert.is(mk.dashify('<!-- comment --> -- not touched'), '<!-- comment --> &ndash; not touched');
assert.is(mk.dashify('a longdash-----is not touched'), 'a longdash-----is not touched');

assert.is(mk.filter('yes &ndash; no &amp; &'), 'yes &ndash; no &amp; &amp;');
assert.is(mk.filter('&#123;, &RightUpVector;, &#x2020;, but &auml'), '&#123;, &RightUpVector;, &#x2020;, but &amp;auml');
assert.is(mk.filter("0 <a href='/get?x=1&y=2'>link</a>"), "0 <a href='/get?x=1&y=2'>link</a>");
assert.is(mk.filter("<i data-etc='&c.' data-name='*this*'>*that* &c.</i>"), "<i data-etc='&c.' data-name='*this*'><b>that</b> &amp;c.</i>");
assert.is(mk.filter('<span>&<span>&<span>'), '<span>&amp;<span>&amp;<span>');
assert.is(mk.filter("if 0<x, I'm *so* going to make this face >_< - I /am/"), "if 0<x, I'm *so* going to make this face >_&lt; - I <i>am</i>");

assert.is(mk.filter('/Url is http://foo.com'), '/Url is http://foo.com');
assert.is(mk.filter('This /might not get italicized:/'), 'This /might not get italicized:/');
assert.is(mk.normalText('<br & />&/'), '<br & />&amp;/');


